Makefile, src/cheri_addr_checks.sail, src/cheri_pc_access.sail
The main changes are due to cleaning up the exception handling functions in sail-riscv, which required some restructuring to sort out dependencies in the cheri model. These changes are with respect to the master-cleanup branch in sail-riscv.
=> fixes to match cleanup in sail-riscv:master-cleanup

src/cheri_cap_common.sail, src/cheri_insts.sail, src/cheri_prelude_128.sail, src/cheri_regs.sail, src/cheri_step_ext.sail, src/cheri_sys_regs.sail
We removed all the implicit casting from sail-riscv, so this commit makes the corresponding changes here.
The bits(5) -> regidx cast is replaced by overloading the readCapReg/writeCapReg functions to take both bitvectors of length 5, and integer indices.
=> Remove all implicit casts in sail-cheri-riscv

Makefile, src/cheri_riscv_types.sail
This depends on https://github.com/rems-project/sail-riscv/pull/33 and thus needs a submodule bump as part of this commit once that pull request has been merged.
=> Bump sail-riscv and provide exception code hooks for CHERI with correct code

src/cheri_cap_common.sail, src/cheri_insts.sail, src/cheri_prelude_128.sail, src/cheri_prelude_64.sail
CCheckPerm/CCheckType have been removed and those opcodes are used for
CRRL/CRAM. This is mostly a copy of the MIPS implementation but I can't
get the sail typechecker to accept my changes.
Pushing this as a PR now so I don't forget
=> WIP: Add CRRL/CRAM

src/cheri_cap_common.sail, src/cheri_insts.sail, src/cheri_prelude_128.sail, src/cheri_prelude_64.sail, src/cheri_properties.sail, src/cheri_sys_exceptions.sail, src/cheri_types.sail
These should all be NFCs. Further work will be needed to support putting sentries in xEPCC and not immediately untagging them due to legalisation, and likely with changes to sail-riscv too as currently prepare_xret_target's return value is masked, whereas it would be helpful for the function itself to have control over/knowledge of the masking in order to determine whether a sealed cap is being modified. We also need to stop legalising CSR/SCRs at write-time and move to the correct read-time legalisation, which already can yield observable differences in edge cases even without CHERI.
=> Code cleanup in preparation for sentries

Makefile, src/cheri_ptw.sail
Uses a SAILCOV environment variable to build sail-coverage support.  It dumps the branch information into generated_definitions/c/all_branches.  This will require the coverage library to be built in the Sail compiler build, under sail/lib/coverage.
=> Add sail-coverage support.

src/cheri_insts.sail, src/cheri_pte.sail, src/cheri_ptw.sail, src/cheri_riscv_types.sail
Things were broken in several ways:
1. Our SC page fault was not tag-dependent
2. We never actually got custom exceptions, just vanilla page faults for missing LoadCap/StoreCap bits
3. We weren't using the recently-added top-level exception codes (what I initially came to fix, before going down the rabbit hole of 1 and 2)
This fixes all of that in a far cleaner way than the highly-duplicated code that was there before. Some of this likely overlaps with Wes's more featureful changes, but we need to get this merged to be able to TestRIG anything with the CHERI PTE bits and those are more invasive. This should then provide a better basis for them to work off.
This depends on https://github.com/rems-project/sail-riscv/pull/62 being merged (and when it is I will update this PR to use the …
=> Fix PTE exceptions

src/cheri_insts.sail
While we generally compare capabilities by virtual address or through other
explicit projections, sometimes (e.g., the CAS involved in revocation) we
really do mean bit-for-bit equality of the encodings.
=> Add CSetEqualExact

src/cheri_insts.sail
This is the existing MIPS description with the register names updated and
converted to markdown.
If this seems reasonable, I'll move over the other descriptions.
=> Add saildoc for CAndPerm

src/cheri_insts.sail
These descriptions are based on the existing MIPS prose (converted to
markdown) with a few minor consistency tweaks.
=> Document CGet* instructions

src/cheri_insts.sail
We currently make sure to handle authorities that went unrepresentable due to a CCopyType, but not those that are still representable yet out of bounds.
Whilst here, reorder the CCSeal checks to match CSeal more (it's a series of branches all doing the same thing, so there's no functional difference) and document both CSeal and CCSeal, hoisting the rather length comments up to the top so as to not clutter the code so much whilst also rendering them more nicely in cheri-architecture.
CSeal_core no longer makes much sense now the length check (which happens quite late for CSeal) isn't shared.
=> Treat CCSeal with an out-of-bounds capability as a move

src/cheri_insts.sail
I have deliberately omitted any details that are not specific to CHERI (i.e. I don't document alignment requirements, translation exceptions or load/store faults as they all apply to things like the normal LW and SW, except for highlighting that capability loads/stores must always be aligned).
=> Add saildoc for non-atomic loads and stores

src/cheri_addr_checks.sail
The matches the latest ISA spec and QEMU
=> Report CHERI exceptions in xTVAL

src/cheri_regs.sail
This was being done in cheri_step_ext.sail, but not here.
=> Also initialize {s,u}ccsr.{d,e}

src/cheri_addr_checks.sail, src/cheri_sys_exceptions.sail, src/cheri_sys_regs.sail, src/cheri_types.sail
These values are reported in xtval, so this information is redundant.
=> Stop reporting cap_cause and cap_index in xCCSR

src/cheri_scr_map.sail
It appears that using a wildcard match triggers a sail C code generation
bug that results in and invalid call to hex_bits_5_matches_prefix()
being generated.
Enumerating all options is an awful workaround but better than crashing.
=> Don't crash when decoding an invalid cspecialrw

.github/workflows/compile.yml
This adds a github action that builds the C emulators for RV32 and RV64, normal and rvfi on each push. Unfortunately compiling sail and install its dependencies each time takes a while and is quite inefficient. We might be able to use a docker file to improve on this but I've not figured out how yet. Fortunately pushes are not that frequent.
=> Github action

Makefile
This adds the new RVFI tracing format and various other improvements.
=> Update sail-riscv submodule and adjust Makefile

src/cheri_insts.sail
Partially fixes #46 . It is only partial because `{lr, sc}.{b, h}` still have to be implemented. The will require a tweak to the sail-riscv spec.
=> Add cap-mode dependent lr / sc and AMOSWAP

Makefile, src/cheri_addr_checks.sail
Pull up to
https://github.com/riscv/sail-riscv/commit/2265a2576fac6d555cfc5f850f78e79c2da56312
Some upstream changes apply to files in this repository as well:
- Following along with
https://github.com/riscv/sail-riscv/commit/b1db5b944b42062d063343db8e2efd05e5889b21
add ext_check_phys_mem_read and ext_check_phys_mem_write implementations.
- Following along with
https://github.com/riscv/sail-riscv/commit/9b38e33c766c7c0397b9d51bf91544db391be670
always use riscv_flen_D.sail rather than riscv_flen_F.sail on RV32.
- Following along with
https://github.com/riscv/sail-riscv/commit/ffea7a39c32a210a446379aeda0eabcec4918ed6
use -fcommon in C_FLAGS.
=> Catch up with upstream sail-riscv

src/cheri_insts.sail
This instruction returns the top of a capability (i.e. one byte past the
end), or an all-ones value for full-address-space capabilities (just
like CGetLen). This can be used instead of a saturating add of base+length.
=> Add CGetTop

src/cheri_insts.sail, src/cheri_reg_type.sail
Split register file support was never implemented and was removed from the specification in https://github.com/CTSRD-CHERI/cheri-specification/pull/10. This commit removes the tiny amount of support for split register files in the model, which was just and always-false `haveSplitRegFile` and the Clear instruction since that is CClear in the merged register file case.
=> Remove support for split register files

Makefile
This does not yet include any of the Zb* or Zk* instructions, but adds various compressed instructions (e.g. hints) that I noticed were missing while fuzzing against QEMU.
Counter-example trace:
```
.4byte 0x00000062 # SLLI hint
.assert rd_wdata == 0x0 "hint"
```
=> Sync default instructions list with sail-riscv

src/cheri_insts.sail
There were 67 occurrences of `not(` vs 31 for `not (`, so I changed those to the more common style. The base RISC-V model doesn't define `not` and uses `~` instead, so maybe we should also use that style?
=> Consistently use `not(` instead of `not (`

.github/workflows/compile.yml
As a bonus opam2 is now available in apt so we can drop the PPA. I think --disable-sandboxing is also no longer required.
=> The github 18.04 action runner is deprecated so upgrade to 20.04.

src/cheri_regs.sail, src/cheri_sys_regs.sail
This can be used by CheriBSD to probe the underlying CHERI semantics while there are still multiple incompatible versions. In the longer term, this register is unlikely to be part of a standardized RISC-V extension, so allocating bits for temporary transitions should be fine.
=> Allocate a feature bit in xCCSR to report tag-clearing semantics

src/cheri_regs.sail, src/cheri_step_ext.sail, src/cheri_sys_regs.sail
It was never used and always hardcoded to one. While touching this code also avoid duplication in ext_init_regs() for the lower-mode CSRs by calling legalize_ccsr(zeros()), which will set the hardwired register bits.
=> Remove the d bit from xccsr

src/cheri_addr_checks.sail
Guard this with get_config_print_platform() to match other exception information print calls.
=> Don't print CHERI exceptions unconditionally

src/cheri_addr_checks.sail, src/cheri_insts.sail
This allows hardware to delay the bounds check. See discussion at https://github.com/CTSRD-CHERI/cheri-specification/issues/54
=> Move bounds check after PC/PCC misalignment checks

src/cheri_addr_checks.sail, src/cheri_insts.sail, src/cheri_prelude.sail, src/cheri_sys_regs.sail
DDC relocation is no longer a mandatory part of the spec and is highly unlikely to be included as part of an initial standardized version of CHERI-RISC-V. In case we do decide to add DDC relocation as an optional extensions, this commit uses a (currently) hardcoded boolean and a helper function (maybe_ddc_relocated_addr) to allow turning it back on again rather than removing the code outright.
See https://github.com/CTSRD-CHERI/cheri-specification/issues/47
=> Disable DDC relocation by default

src/cheri_insts.sail
This updates CSpecialRW to include the new value that was written to the CSR which helps when scanning traces for the latest value.
=> Print CHERI SCR updates in traces

src/cheri_addr_checks.sail, src/cheri_cap_common.sail, src/cheri_insts.sail, src/cheri_misa_ext.sail, src/cheri_pc_access.sail, src/cheri_prelude.sail, src/cheri_sys_exceptions.sail, src/cheri_sys_regs.sail
This is somewhat more invasive than the change to disable DDC relocation, so we might want to remove the fallback code outright rather than keeping a have_pcc_relocation() configuration option.
=> Disable PCC relocation by default

LICENCE
Add Google for Alex's contributions after joining Google.
=> LICENCE: Extend copyright range to 2023.

src/cheri_addr_checks.sail
It needs to be on the `val`, adding it to the `function` prevents it from being visible in the CHERI specification.
=> Fix LaTeX documentation for ddc_and_result_addr

Makefile
These are part of the mandatory RVA22 profile, so it makes sense to include them here. Future changes could be changing the semantics of Zba to return capabilities instead of integers, but the instructions can also be useful as defined right now.
=> Include the Zb* extension

Makefile, handwritten_support/c_emulator_fix.c, src/cheri_prelude.sail, src/cheri_regs.sail, test/run_tests.sh
Following #91, additionally catch up with the latest sail 0.17.2 and sail-riscv. Fix emulators (see commit message). 
Tested on macOS and Ubuntu 22.04.2 (both AArch64 though). Both emulators pass all tests:
````
test/run_tests.sh
...
64-bit RISCV OCaml tests: Passed 184 out of 184
64-bit RISCV C tests: Passed 230 out of 230
```
=> Fix emulators and tests
